/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package U3A6_Markspackage;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author anarc6700
 */
public class MarksFrame extends javax.swing.JFrame {
 ArrayList <Integer> grades = new ArrayList();
 
    /**
     * Creates new form MarksFrame
     */
    public MarksFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gradeinput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradearea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        grademath = new javax.swing.JTextArea();
        sortbutton = new javax.swing.JButton();
        analyzebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 56, 208));
        jLabel1.setText("Marks Program");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Student Mark ");

        gradeinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeinputActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        gradearea.setColumns(20);
        gradearea.setRows(5);
        jScrollPane1.setViewportView(gradearea);

        grademath.setColumns(20);
        grademath.setRows(5);
        jScrollPane2.setViewportView(grademath);

        sortbutton.setText("Sort ");
        sortbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbuttonActionPerformed(evt);
            }
        });

        analyzebutton.setText("Analyze");
        analyzebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzebuttonActionPerformed(evt);
            }
        });

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradeinput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(sortbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(analyzebutton)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortbutton)
                    .addComponent(analyzebutton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradeinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeinputActionPerformed

    private void sortbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbuttonActionPerformed
        //sorts the grades from lowest to highest
        Collections.sort(grades);
        //displays the grades in the sorted order 
         for(int i=0; i< grades.size(); i++){
            System.out.println(i);
           gradearea.append(grades.get(i) +"\n" );
          
         }
    }//GEN-LAST:event_sortbuttonActionPerformed

    private void analyzebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzebuttonActionPerformed
        int maximumMark;
        int minMark = marksLow();
       int average = average();
        maximumMark = marksMax();
    int fun = 0;
    int sum1=0;
    int sum2 =0;
    int sum3 = 0;
    int sum4 = 0;
    int sum5 = 0;
    // sorts the grades into diffrent tiers
        for (int i=0;i<grades.size();i++){
        System.out.println(i);
        fun = grades.get(i);
        if(fun<50){
            sum1 ++;
        }else if((fun >= 50) && (fun < 60) ){
            sum2 ++;
        }else if((fun >= 60) && (fun < 70) ){
            sum3++;    
       }else if((fun >= 70) && (fun < 80) ){
           sum4++;
       }else if (fun >= 80){
            sum5++;
        }
    }
    // displayes the average, range and the tiers
    grademath.append("The average is %" + average + "\n");    
    grademath.append("Range of Marks " + ( maximumMark - minMark) + "\n" );
    grademath.append("Number at level R:" + sum1 + "\n" );
    grademath.append("Number at level 1:" + sum2 + "\n" );
    grademath.append("Number at level 2:" + sum3 + "\n" );
    grademath.append("Number at level 3:" + sum4 + "\n" );
    grademath.append("Number at level 4:" + sum5 + "\n" );
   
    }//GEN-LAST:event_analyzebuttonActionPerformed
    
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
      // adds the input text to the grades string 
        grades.add(Integer.parseInt(gradeinput.getText()));   
    }//GEN-LAST:event_addbuttonActionPerformed

    public int marksMax(){
        int maximum=0;
        
        // for structure that compares the index values and saves the higher one
        for (int i=0;i<grades.size();i++){
            if (grades.get(i)>maximum){
                maximum = grades.get(i);
            }
        }
        return maximum;
    }
    public int marksLow(){
       // uses the sort function to find the lowest number
       int lowest =  grades.get(0);
       return lowest;
    }
  public int average(){
      
      int average = 0;
      int sum=0;
      //add each element in the string and divides the sum by the string lenght 
      for(int i=0; i<grades.size(); i++){
          sum+=grades.get(i);
          average = (sum / grades.size());
      }
      return average;
  }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarksFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton analyzebutton;
    private javax.swing.JTextArea gradearea;
    private javax.swing.JTextField gradeinput;
    private javax.swing.JTextArea grademath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sortbutton;
    // End of variables declaration//GEN-END:variables
}
